const fs = require("fs-extra");
const { createCanvas } = require("canvas");
const db = require("../config/db");
const dayjs = require("dayjs");

async function generateSummaryImage(outputPath) {
  try {
    // Get top 5 countries by estimated_gdp efficiently
    const result = await db.query(`
      SELECT name, estimated_gdp 
      FROM countries 
      WHERE estimated_gdp IS NOT NULL AND estimated_gdp > 0 
      ORDER BY estimated_gdp DESC 
      LIMIT 5
    `);
    const top5 = result.rows;

    const totalResult = await db.query("SELECT COUNT(*) as count FROM countries");
    const total = parseInt(totalResult.rows[0].count) || 0;

    // Create canvas
    const width = 1000;
    const height = 700;
    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext("2d");

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, width, height);

    // Add border
    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 2;
    ctx.strokeRect(10, 10, width - 20, height - 20);

    // Title
    ctx.fillStyle = "#1a1a1a";
    ctx.font = "bold 36px Arial";
    ctx.fillText("Country Data Summary", 40, 60);

    // Timestamp
    ctx.fillStyle = "#666666";
    ctx.font = "18px Arial";
    ctx.fillText(`Generated: ${dayjs().format("YYYY-MM-DD HH:mm:ss")}`, 40, 95);

    // Total countries
    ctx.fillStyle = "#1a1a1a";
    ctx.font = "24px Arial";
    ctx.fillText(`Total Countries: ${total}`, 40, 150);

    // Top 5 header
    ctx.fillStyle = "#333333";
    ctx.font = "bold 28px Arial";
    ctx.fillText("Top 5 by Estimated GDP", 40, 210);

    // Draw top 5 countries
    let y = 260;
    ctx.font = "20px Arial";

    for (let i = 0; i < top5.length; i++) {
      const country = top5[i];
      const gdp = Number(country.estimated_gdp).toLocaleString("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 0,
      });

      // Rank circle
      ctx.fillStyle = "#4285f4";
      ctx.beginPath();
      ctx.arc(60, y - 8, 18, 0, Math.PI * 2);
      ctx.fill();

      // Rank number
      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 18px Arial";
      ctx.textAlign = "center";
      ctx.fillText(`${i + 1}`, 60, y);

      // Country name
      ctx.fillStyle = "#1a1a1a";
      ctx.font = "bold 22px Arial";
      ctx.textAlign = "left";
      ctx.fillText(country.name, 100, y);

      // GDP value
      ctx.fillStyle = "#666666";
      ctx.font = "20px Arial";
      ctx.fillText(gdp, 100, y + 28);

      y += 70;
    }

    // Footer
    ctx.fillStyle = "#999999";
    ctx.font = "16px Arial";
    ctx.fillText("Generated by Country Currency Exchange API", 40, height - 40);

    // Save to file
    const buffer = canvas.toBuffer("image/png");
    fs.writeFile(outputPath, buffer);

    console.log(`✓ Summary image saved to ${outputPath}`);
  } catch (err) {
    console.error("Image generation error:", err.message);
  }
}

module.exports = { generateSummaryImage };
